---
# Install OS specific beats

- name: Include specific Beats
  include: beats-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Beats
  include: beats-redhat.yml
  when: ansible_os_family == 'RedHat'

#Configuration file for beats
- name: Beats configuration
  include: beats-config.yml

# Make sure the service is started, and restart if necessary
- name: Start beats service
  service:
    name: "{{ beats_beat }}"
    state: started
    enabled: yes
  when: beats_start_service
  register: beats_started
