VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/centos-7.3"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
  end

  config.vm.define "beats1" do |beats1|
    beats1.vm.hostname = "beats1"
    beats1.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.provision "shell", inline: '[ -f /etc/redhat-release ] && sudo yum -y install epel-release; which lsb_release 2>/dev/null && [ $(lsb_release -s -i) = "Ubuntu" -a $(lsb_release -s -r | tr -d "." ) -ge 1604 ] && sudo apt-get -y install python-simplejson; true'

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
